Repository PoMaKoM-RSTeam/send-to-telegram-front, pull requests merged in 2022-01, with the labels that each got.

#5 add: Git Ignore
  .gitignore
Labels: feature

#8 add: add MPL license
  LICENSE
Labels: documentation

#7 add: ESLint and ESLintignore
  .eslintignore
  .eslintrc
  package-lock.json
Labels: feature

#10 Add react-typescript
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.scss
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
Labels: feature

#13 add: Prettier
  .prettierrc
  package.json
Labels: feature, wontfix

#11 docs: populated the readme file with project info
  README.md
Labels: documentation, wontfix

#16 feat: add husky & pre-commit hook
  .husky/.gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: feature

#20 add: Node-engines
  package.json
Labels: feature

#22 feat: add eslint-airbnb
  .eslintrc
  package-lock.json
  package.json
  public/manifest.json
Labels: feature

#23 feat: add login button in telegram
  package-lock.json
  package.json
  src/App.scss
  src/App.tsx
Labels: feature

#26 Feature/s1/fr 32/add routing
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/pages/error.tsx
  src/pages/login.tsx
  src/pages/main.tsx
  src/scss/login.scss
  src/scss/main.scss
Labels: feature

#27 add: add-structure-display-frame
  src/App.tsx
  src/pages/Login/login.scss
  src/pages/Login/login.tsx
  src/pages/login.tsx
  src/scss/login.scss
Labels: feature

#29 Feature/s1/fr 26/add page user
  src/Components/PageUser/PageUser.scss
  src/Components/PageUser/PageUser.tsx
  src/pages/Login/login.scss
  src/pages/Login/login.tsx
Labels: feature

#28 Feature/s1/fr 25/add dashboard
  package-lock.json
  src/App.tsx
  src/Components/ConsoleBot/ConsoleBot.scss
  src/Components/ConsoleBot/ConsoleBot.tsx
  src/Components/ConsoleBot/ConsoleBotItem/ConsoleBotItem.scss
  src/Components/ConsoleBot/ConsoleBotItem/ConsoleBotItem.tsx
  src/pages/Login/login.scss
  src/pages/Login/login.tsx
Labels: feature
